import psycopg2

def insert_dummy_data():
    db_params = {
        "dbname": "postgres", "user": "postgres",
        "password": "1546985", "host": "127.0.0.1", "port": "5432"
    }

    # The %s act as placeholders. This is an elegant, secure way to insert data 
    # (parameterized queries) that prevents formatting errors and security risks.
    sql_insert = """
    INSERT INTO water_levels (sensor_id, water_level_cm)
    VALUES (%s, %s)
    RETURNING id, recorded_at;
    """
    
    # Let's simulate a 45.5 cm water level reading from a local sensor
    sensor_data = ("Ternate_Sensor_01", 45.5)

    try:
        with psycopg2.connect(**db_params) as conn:
            with conn.cursor() as cur:
                cur.execute(sql_insert, sensor_data)
                
                # Fetch the ID and automatic timestamp generated by PostgreSQL
                new_id, timestamp = cur.fetchone()
                
                # We MUST commit the transaction to save it permanently
                conn.commit()
                
        print(f"✅ Success! Saved reading #{new_id} from Ternate_Sensor_01 at {timestamp}")
        
    except Exception as e:
        print(f"❌ Error: {e}")

if __name__ == "__main__":
    insert_dummy_data()